export type AuthenticationErrorCode =
	| 'CURRENT_PASSWORD_INCORRECT'
	| 'EMAIL_NOT_VERIFIED'
	| 'EXPIRED_GOOGLE_AUTH_STATE'
	| 'GOOGLE_AUTH_CREDENTIALS_REQUIRED'
	| 'GOOGLE_ID_TOKEN_MISSING'
	| 'INTEGRATION_USER_NOT_FOUND'
	| 'INVALID_GOOGLE_ID_TOKEN_PAYLOAD'
	| 'INVALID_TOKEN'
	| 'USER_NO_PASSWORD_USE_SOCIAL_LOGIN'
	| 'USER_OR_PASSWORD_INCORRECT';
