import { HttpResponse } from '@wppsync/backend';

import { ApplicationError, type ApplicationErrorCode } from '@/entities/errors/index.js';

const APPLICATION_ERROR_STATUS = {
	INVALID_TOKEN: 401,
	USER_EMAIL_ALREADY_EXISTS: 400,
	USER_NOT_FOUND: 404,
	USER_NO_PASSWORD_USE_SOCIAL_LOGIN: 400,
	USER_OR_PASSWORD_INCORRECT: 401,
	WORKSPACE_NOT_FOUND: 404,
	MEMBER_NOT_FOUND: 404,
	MEMBER_ALREADY_OWNER: 400,
	CONTACT_NOT_FOUND: 404,
	CONTACT_ALREADY_EXISTS: 400,
	CONTACT_STAGE_NOT_FOUND: 404,
	CONTACT_STAGE_ALREADY_EXISTS: 409,
	CONVERSATION_CLOSED: 409,
	INVALID_CONVERSATION_PARTICIPANT: 400,
	CONVERSATION_NOT_FOUND: 404,
	CONVERSATION_PARTICIPANT_NOT_FOUND: 404,
	CONVERSATION_PARTICIPANT_CREATION_FAILED: 500,
	INVALID_MESSAGE: 400,
	MESSAGE_NOT_FOUND: 404,
	INTEGRATION_NOT_FOUND: 404,
	INVITE_NOT_FOUND: 404,
	INVITE_SAME_EMAIL: 409,
	INVITE_BELONGS_ANOTHER: 400,
	INVALID_IMAGE: 400,
	UNSUPPORTED_FILE_TYPE: 400,
	PERMISSION_DENIED: 403
} satisfies Record<ApplicationErrorCode, number>;

export function mapApplicationError(error: ApplicationError): HttpResponse {
	return HttpResponse.error(APPLICATION_ERROR_STATUS[error.code], error.code, {
		message: error.message,
		...error.data
	});
}
