import { HttpResponse } from '@wppsync/backend';

import { ApplicationError, type ApplicationErrorCode } from '@/entities/errors/index.js';

const APPLICATION_ERROR_STATUS = {
	CURRENT_PASSWORD_INCORRECT: 400,
	EMAIL_NOT_VERIFIED: 401,
	EXPIRED_GOOGLE_AUTH_STATE: 401,
	GOOGLE_AUTH_CREDENTIALS_REQUIRED: 400,
	GOOGLE_ID_TOKEN_MISSING: 401,
	INTEGRATION_USER_NOT_FOUND: 400,
	INVALID_GOOGLE_ID_TOKEN_PAYLOAD: 401,
	INVALID_TOKEN: 401,
	TURNSTILE_CONFIGURATION_ERROR: 503,
	TURNSTILE_UNAVAILABLE: 503,
	TURNSTILE_VERIFICATION_FAILED: 400,
	USER_EMAIL_ALREADY_EXISTS: 400,
	USER_NOT_FOUND: 404,
	USER_NO_PASSWORD_USE_SOCIAL_LOGIN: 400,
	USER_OR_PASSWORD_INCORRECT: 401,
	WORKSPACE_LIMIT_REACHED: 409,
	WORKSPACE_NOT_FOUND: 404,
	MEMBER_NOT_FOUND: 404,
	MEMBER_ALREADY_OWNER: 400,
	CONTACT_NOT_FOUND: 404,
	CONTACT_ALREADY_EXISTS: 400,
	CONTACT_STAGE_NOT_FOUND: 404,
	CONTACT_STAGE_ALREADY_EXISTS: 409,
	CONVERSATION_CLOSED: 409,
	INVALID_CONVERSATION_PARTICIPANT: 400,
	CONVERSATION_NOT_FOUND: 404,
	CONVERSATION_PARTICIPANT_NOT_FOUND: 404,
	CONVERSATION_PARTICIPANT_CREATION_FAILED: 500,
	INVALID_MESSAGE: 400,
	MESSAGE_NOT_FOUND: 404,
	INTEGRATION_NOT_FOUND: 404,
	INVITE_NOT_FOUND: 404,
	INVITE_SAME_EMAIL: 409,
	INVITE_BELONGS_ANOTHER: 400,
	INVALID_IMAGE: 400,
	UNSUPPORTED_FILE_TYPE: 400,
	PERMISSION_DENIED: 403
} satisfies Record<ApplicationErrorCode, number>;

export function mapApplicationError(error: ApplicationError): HttpResponse {
	return HttpResponse.error(APPLICATION_ERROR_STATUS[error.code], error.code, {
		message: error.message,
		...error.data
	});
}
