export type ConversationErrorCode =
	| 'CONVERSATION_CLOSED'
	| 'CONVERSATION_NOT_FOUND'
	| 'CONVERSATION_PARTICIPANT_NOT_FOUND'
	| 'INVALID_CONVERSATION_PARTICIPANT'
	| 'CONVERSATION_PARTICIPANT_CREATION_FAILED'
	| 'INVALID_MESSAGE'
	| 'MESSAGE_NOT_FOUND';
