import type { Contact, RelationshipStage } from './types';

export const initialRelationshipStages: RelationshipStage[] = [
	{
		id: 'lead',
		name: 'Lead',
		color: '#f59e0b',
		icon: 'person',
		description: 'Contato novo que ainda está em qualificação.',
		order: 0
	},
	{
		id: 'waiting',
		name: 'Aguardando',
		color: '#0ea5e9',
		icon: 'clock',
		description: 'Depende de uma resposta ou ação do contato.',
		order: 1
	},
	{
		id: 'client',
		name: 'Cliente',
		color: '#25d366',
		icon: 'check',
		description: 'Relacionamento convertido em cliente ativo.',
		order: 2
	},
	{
		id: 'inactive',
		name: 'Inativo',
		color: '#94a3b8',
		icon: 'pause',
		description: 'Contato sem interação ou oportunidade ativa.',
		order: 3
	}
];

export const initialContacts: Contact[] = [
	{
		id: 'juliana-costa',
		name: 'Juliana Costa',
		initials: 'JC',
		phone: '+55 31 98765-4321',
		email: 'juliana.costa@email.com',
		company: 'Ateliê Aurora',
		city: 'Belo Horizonte, MG',
		stageId: 'lead',
		tags: ['Lead quente', 'Instagram'],
		lastInteraction: 'Hoje, 11:42',
		lastInteractionOrder: 10,
		firstContact: '15 mai 2025',
		origin: 'Instagram',
		conversations: 7,
		lastMessage: 'Gostaria de saber mais sobre os valores.',
		notes: 'Demonstrou interesse no plano Profissional. Retomar o contato na quinta-feira.',
		favorite: true
	},
	{
		id: 'lucas-mendes',
		name: 'Lucas Mendes',
		initials: 'LM',
		phone: '+55 11 91234-5678',
		email: 'lucas@movestudio.com.br',
		company: 'Move Studio',
		city: 'São Paulo, SP',
		stageId: 'client',
		tags: ['Cliente', 'E-commerce'],
		lastInteraction: 'Hoje, 11:28',
		lastInteractionOrder: 9,
		firstContact: '02 abr 2025',
		origin: 'Indicação',
		conversations: 12,
		lastMessage: 'Perfeito, obrigado pelo atendimento!',
		notes: 'Cliente recorrente. Prefere contato no período da manhã.'
	},
	{
		id: 'ana-paula',
		name: 'Ana Paula Ribeiro',
		initials: 'AR',
		phone: '+55 21 99876-5432',
		email: 'ana.ribeiro@email.com',
		city: 'Rio de Janeiro, RJ',
		stageId: 'waiting',
		tags: ['Aguardando', 'Produto'],
		lastInteraction: 'Hoje, 10:57',
		lastInteractionOrder: 8,
		firstContact: '22 jul 2025',
		origin: 'WhatsApp',
		conversations: 3,
		lastMessage: 'Vocês têm disponível na cor preta?',
		notes: 'Aguardando confirmação de estoque do produto preto.'
	},
	{
		id: 'empresa-alpha',
		name: 'Empresa Alpha',
		initials: 'EA',
		phone: '+55 31 3333-2100',
		email: 'contato@alpha.com.br',
		company: 'Empresa Alpha Ltda.',
		city: 'Contagem, MG',
		stageId: 'lead',
		tags: ['Empresa', 'B2B'],
		lastInteraction: 'Hoje, 10:45',
		lastInteractionOrder: 7,
		firstContact: '18 jul 2025',
		origin: 'Site',
		conversations: 4,
		lastMessage: 'Podemos agendar uma reunião para sexta?',
		notes: 'O decisor é o Marcos. Preparar proposta para 15 usuários.'
	},
	{
		id: 'carlos-eduardo',
		name: 'Carlos Eduardo',
		initials: 'CE',
		phone: '+55 41 99111-2233',
		email: 'carlos.edu@email.com',
		city: 'Curitiba, PR',
		stageId: 'client',
		tags: ['Cliente', 'Premium'],
		lastInteraction: 'Ontem, 17:20',
		lastInteractionOrder: 6,
		firstContact: '11 fev 2025',
		origin: 'Google',
		conversations: 18,
		lastMessage: 'Pagamento realizado ✅',
		notes: 'Plano anual. Renovação prevista para fevereiro.'
	},
	{
		id: 'patricia-lima',
		name: 'Patrícia Lima',
		initials: 'PL',
		phone: '+55 51 98888-1122',
		email: 'patricia.lima@email.com',
		city: 'Porto Alegre, RS',
		stageId: 'client',
		tags: ['Cliente', 'Varejo'],
		lastInteraction: 'Ontem, 14:08',
		lastInteractionOrder: 5,
		firstContact: '08 jan 2025',
		origin: 'Facebook',
		conversations: 9,
		lastMessage: 'Qual é o prazo de entrega?',
		notes: ''
	},
	{
		id: 'renato-oliveira',
		name: 'Renato Oliveira',
		initials: 'RO',
		phone: '+55 85 99654-2020',
		email: 'renato@oliveiratech.io',
		company: 'Oliveira Tech',
		city: 'Fortaleza, CE',
		stageId: 'waiting',
		tags: ['Demonstração', 'SaaS'],
		lastInteraction: '28 jul, 16:34',
		lastInteractionOrder: 4,
		firstContact: '28 jul 2025',
		origin: 'LinkedIn',
		conversations: 2,
		lastMessage: 'Vou validar com meu sócio e retorno.',
		notes: 'Enviar comparativo de planos caso não responda em 3 dias.'
	},
	{
		id: 'mariana-souza',
		name: 'Mariana Souza',
		initials: 'MS',
		phone: '+55 61 99902-7741',
		email: 'mariana.souza@email.com',
		city: 'Brasília, DF',
		stageId: 'inactive',
		tags: ['Newsletter'],
		lastInteraction: '12 jun, 09:15',
		lastInteractionOrder: 3,
		firstContact: '20 nov 2024',
		origin: 'Landing page',
		conversations: 1,
		lastMessage: 'Obrigada pelas informações.',
		notes: 'Sem interesse no momento. Manter apenas na newsletter.'
	}
];
