export type WorkspaceErrorCode =
	| 'WORKSPACE_NOT_FOUND'
	| 'WORKSPACE_LIMIT_REACHED'
	| 'MEMBER_NOT_FOUND'
	| 'MEMBER_ALREADY_OWNER'
	| 'INVITE_NOT_FOUND'
	| 'INVITE_SAME_EMAIL'
	| 'PERMISSION_DENIED';
